### PR TITLE
Some libs and examples

### PR DESCRIPTION
**Pull request by totorigolo**
Soooooo, this PR is quite big. I know, that's bad. That's some of my local changes I had before the directoryquake. But this should be quite easy to review since every commit should be atomic.

**However**, this PR requires Z3 in order to pass the CI (@andreaslindner, what's the status?).

### CODE REVIEW

**Comment by andreaslindner** [comment]
let's do it like this: we add it in the CI setup phase and add a simple test in one comment and a separate PR. if this works, we rebase it into master and rebase this one on top of it and let the CI deal with the problem :)

**Comment by andreaslindner** [comment]
could you try the first step or do you need my help for this? you just need to add another line to the before_script parts of the two prepare jobs in the travis file. this should be the install_z3 script. the rest should work magically if i didn't leave something for us to debug in these scripts 😄

**Comment by totorigolo** [comment]
Rebased on master.

**Comment by totorigolo** [comment]
The commit order seems wrong on GitHub, because they are not in chronological order (because :cherries:-pick and rebase magic). Keep that in mind when reviewing :slightly_smiling_face:

**Comment by andreaslindner** [comment]
So if I use some git GUI tools it would probably be correct since I'm looking at the actual commit order not timestamps, right?

**Comment by totorigolo** [comment]
Yep, I think so. If you have any doubt, check with `git log` :slightly_smiling_face:

**Pull request merged**
