### PR TITLE
Added more conditional rewriting theorems in bir_bool_equivScript.sml

### PR DESCRIPTION
**Pull request by didriklundberg**
What the title says. This should be useful when reducing BIR expressions to something that an SMT solver can chew on.

### CODE REVIEW

**Comment by totorigolo** [comment]
Completely unrelated to the actual changes, but can you rebase you branch to avoid having a merge commit?

I'm looking into the code now :slightly_smiling_face:

**Comment by didriklundberg** [comment]
> Completely unrelated to the actual changes, but can you rebase you branch to avoid having a merge commit?

Ok, I used some Jedi powers that I think solved the issue.

**Comment by totorigolo** [comment]
Wait, why do you need the hypothesis in `bir_disj_equiv`? `bir_and_equiv` is almost the same and doesn't have them @didriklundberg

**Comment by didriklundberg** [comment]
> Wait, why do you need the hypothesis in `bir_disj_equiv`? `bir_and_equiv` is almost the same and doesn't have them @didriklundberg

It follows directly from the semantics of BIR conjunction that both conjuncts are Boolean. This is not the case for BIR disjunction, in which only one of the disjuncts is required to be Boolean for the disjunction to hold. Accordingly, to map onto HOL disjunction we must require that both disjuncts be Boolean.

**Comment by totorigolo** [comment]
That makes sense, thanks :)

**Pull request merged**
