### PR TITLE
CI: Now greps for cheat and comment the PR

### PR DESCRIPTION
**Pull request by totorigolo**
What the title says.

If this PR is successful, we should see a comment from the new HolBA bot.

Closes: #52

### CODE REVIEW

**Comment by totorigolo** [comment]
This PR adds ~40 sec + the time to boot a VM of latency to the CI process.

**Comment by andreaslindner** [comment]
> This PR adds ~40 sec + the time to boot a VM of latency to the CI process.

I think there is a lot of variance in the job execution time that it is hard to tell this from one run. Also, I don't think it could add so much. Or how did you get the 40 seconds?

**Comment by andreaslindner** [comment]
This is really nice, and the holba-bot icon also has something resembling horns ;)

**Comment by andreaslindner** [comment]
i didn't check, could you explain the global secret property? i guess this is travis naming but it doesn't seem very secure if a secret is out in the public :)

**Comment by totorigolo** [comment]
> This is really nice, and the holba-bot icon also has something resembling horns ;)

Oops, I just changed the profile picture :innocent: 


> i didn't check, could you explain the global secret property? i guess this is travis naming but it doesn't seem very secure if a secret is out in the public :)

This is the `HOLBA_BOT_GITHUB_TOKEN` environment variable, encrypted using the `travis` CLI.

> Looks good! could you mention the corresponding issue and fix the CONTRIBUTING.md file accordingly in an additional commit? or is there something missing for this?

I mentioned the issue in the PR (I edited), but I can also mention in the commit. Regarding the `CONTRIBUTING.md`, you're right I forgot it :)

**Pull request merged**
