### PR TITLE
Use Python 3

### LINKED ISSUE #40: Change python2 to python3

### PR DESCRIPTION
**Pull request by totorigolo**
Chat the title says. Everything should still work fine (and the CI will confirm :slightly_smiling_face:).

Closes #40

### CODE REVIEW

**Comment by andreaslindner** [comment]
We need to check whether we can have `python3` also here:
```
scripts/ci/grep-cheat-comment-PR.sh:    printf '%s' "$1" | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))'
scripts/setup/install_z3_src.sh:python scripts/mk_make.py --prefix=${Z3_DIR} --python --pypkgdir=${Z3_DIR}/bin/python
```

... and write python2 here (no need to fix this one...):
```
doc/gen/dependencies.py:#!/usr/bin/python
```

then this should close #40

**Comment by totorigolo** [comment]
I think that you should have used `./script.py` instead :slightly_smiling:

https://github.com/kth-step/HolBA/blob/d2ca1032433cf96accabab9cfc85d7fe2f20ab71/scripts/setup/install_z3_src.sh#L55

**Comment by andreaslindner** [comment]
okay, I could try this later. but what is the benefit of one over the other?

**Comment by totorigolo** [comment]
Because then there is no need to say it twice, the shebang is enough :)

**Comment by andreaslindner** [comment]
Do you mean creating a script.py file with this behavior? Otherwise I cannot find this file

**Comment by totorigolo** [comment]
I just meant that you can just execute `./script.py` thanks to the [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) :wink:

**Comment by andreaslindner** [comment]
ah ok. but i'm still unsure whether i get you right. if you talk about the script scripts/mk_make.py. there is no shedingdong, see:
https://github.com/Z3Prover/z3/blob/master/scripts/mk_make.py

and even if there was one, it could be referring to just python, and i may want to be specific to use python3 for systems which are more legacy driven :)

**Comment by totorigolo** [comment]
Right, I didn't notice that you don't own this file. Then, nevermind :innocent:

**Pull request merged**
