### PR TITLE
bundled version of l3 riscv model and step

### PR DESCRIPTION
**Pull request by palmskog**
@didriklundberg is this what you had in mind? I took the latest files from the `dev_riscv_l3_t1_2` branch.

### CODE REVIEW

**Comment by didriklundberg** [comment]
> @didriklundberg is this what you had in mind? I took the latest files from the `dev_riscv_l3_t1_2` branch.

No, take the files from `trindemossen-1` as I wrote on Zulip. Then I will contribute my changes on top of those files. Also, I see you did not add [the copyright notice of the "HOL4 CONTRIBUTORS"](https://github.com/HOL-Theorem-Prover/HOL/blob/develop/COPYRIGHT).

**Comment by palmskog** [comment]
@didriklundberg OK now?

**Comment by didriklundberg** [comment]
> @didriklundberg OK now?

You forgot to remove [riscv_stepSimps.sig](https://github.com/kth-step/HolBA/pull/195/commits/15585065323cba7c927a1e5e4c8ccf88013fd62f#diff-e42b38a81ed76d238ba24eac0d6796c5e638db0b0059bc6e32b76e782fcfcbdf) and [riscv_stepSimps.sml](https://github.com/kth-step/HolBA/pull/195/commits/15585065323cba7c927a1e5e4c8ccf88013fd62f#diff-fb6f87e976ea5486874510f4767c10b9989d05d494553a5b03830903bd255ec1).

**Comment by didriklundberg** [comment]
Okay, I added the changes now. [Here](https://github.com/kth-step/HolBA/pull/196)'s a PR into `l3-riscv` with the additions on the HolBA side, which I suggest we handle before merging this PR.

**Comment by palmskog** [comment]
@didriklundberg apparently an ARM(!) self test is failing, could you take a look?
```
 Failed tests: (1 total)
- src/tools/lifter/selftest_arm.exe
```

**Comment by didriklundberg** [comment]
> @didriklundberg apparently an ARM(!) self test is failing, could you take a look?
> 
> ```
>  Failed tests: (1 total)
> - src/tools/lifter/selftest_arm.exe
> ```

Looks like two failing instructions switching order: benign, but unexpected. Let me take a look at what could have caused this.

**Comment by didriklundberg** [comment]
> @didriklundberg apparently an ARM(!) self test is failing, could you take a look?
> 
> ```
>  Failed tests: (1 total)
> - src/tools/lifter/selftest_arm.exe
> ```

The reason for failure is the change to [src/tools/lifter/selftestLib.sml](https://github.com/kth-step/HolBA/pull/195/commits/41a1c371b6bdb8f0b2f640faf40d759bd99b1d80#diff-3a7de0e5745b5d01540a10961c1647288ba93b5f6b382f25b661589d20178d88) which now lists lifter failures in order of occurrence, rather than reverse order of occurrence. I suggest pushing the updated arm8 selftest log: if you think this is solution is OK, I can fix it.

**Comment by palmskog** [comment]
> I suggest pushing the updated arm8 selftest log: if you think this is solution is OK, I can fix it.

Please go ahead and fix, also feel free to merge this into `riscv-symbexec` when it makes CI green.

**Pull request merged**
