### PR TITLE
Add symbolic execution, and also fix some issues after the Holmakefile change, reactivated testing and testing with CI

### PR DESCRIPTION
**Pull request by andreaslindner**
The failing CI is due to reactivation of CI testing. It actually fixes several issues.

### CODE REVIEW

**Comment by palmskog** [comment]
@andreaslindner this is fine to merge by me, but maybe the failing test cases in CI can be disabled for the time being, so we get a green checkmark? Then @didriklundberg and I can work on fixing them when Didrik has time.

**Comment by didriklundberg** [comment]
> @andreaslindner this is fine to merge by me, but maybe the failing test cases in CI can be disabled for the time being, so we get a green checkmark? Then @didriklundberg and I can work on fixing them when Didrik has time.

Yes, that would also be fine by me.

**Comment by guancio** [comment]
I think we need to clarify which tests have to remain and which ones are legacy. The ones that should remain should pass, otherwise we are going to loose functionalities while doing this porting.

**Comment by palmskog** [comment]
@guancio as we have discussed elsewhere, the following are the tests that were run in CI before:

- examples/bsl-wp-smt/test-addrs-eq-imp-x42.exe
- examples/bsl-wp-smt/test-cjmp.exe
- examples/bsl-wp-smt/test-gauss-no-mem.exe
- examples/tutorial/test-composition.exe
- src/shared/HolSmt/selftest.exe
- src/shared/examples/test-bir-to-word-to-z3-sat-model.exe
- src/shared/examples/test-bir-to-word.exe
- src/shared/examples/test-bsl-progs.exe
- src/shared/examples/test-json.exe
- src/shared/examples/test-smtLib.exe
- src/shared/examples/test-z3-sat-model.exe
- src/shared/examples/test-z3_wrapper.exe
- src/theory/bir-support/selftest.exe
- src/theory/bir/selftest.exe
- src/tools/cfg/examples/test-cfg.exe
- src/tools/cfg/examples/test-collections.exe
- src/tools/comp/examples/test-bir_populate_elist_predset.exe
- src/tools/exec/examples/test-basic.exe
- src/tools/exec/examples/test-obs.exe
- src/tools/lifter/selftest_arm.exe
- src/tools/lifter/selftest_riscv.exe
- src/tools/scamv/obsmodel/test-bir_obs_model.exe
- src/tools/scamv/symbexec/examples/test-minimal.exe
- src/tools/scamv/test-bir_utilLib.exe
- src/tools/scamv/test-scamv_enumLib.exe
- src/tools/wp/examples/test-toy.exe
- src/tools/wp/examples/test-wp.exe

The following tests are failing after the new CI build in this PR, and I propose that Didrik and I together aim to fix them very soon:

- examples/bsl-wp-smt/test-addrs-eq-imp-x42.exe
- src/tools/cfg/examples/test-cfg.exe
- src/tools/cfg/examples/test-collections.exe
- src/tools/comp/examples/test-bir_populate_elist_predset.exe
- src/tools/exec/examples/test-basic.exe
- src/tools/exec/examples/test-obs.exe
- src/tools/scamv/symbexec/examples/test-minimal.exe

What I propose is that in the interest of merging this PR quickly *and* having a green build in CI, we *temporarily* deactivate the failing tests.

**Review by didriklundberg — APPROVED** [review]

**Pull request merged**
