### PR TITLE
Fixed typo in bir_inst_liftingScript.sml

### PR DESCRIPTION
**Pull request by didriklundberg**
I fixed the typo in `bir_inst_liftingScript.sml` (closes https://github.com/kth-step/HolBA/issues/44) and adjusted the proof accordingly. Nothing else seems to be affected.

### CODE REVIEW

**Comment by totorigolo** [comment]
**Quick tip**: to enable GitHub magic, write `Closes #44` in the commit message or in the PR description. That way, GitHub will automatically close the related Issue when this PR will be merged. I think that you can just replace `mentioned in #44` by `closes #44` and that should do it.

**Comment by andreaslindner** [comment]
I changed Didrik's comment :D. let's see whether it works when we merge it later.

**Comment by didriklundberg** [comment]
> **Quick tip**: to enable GitHub magic, write `Closes #44` in the commit message or in the PR description. That way, GitHub will automatically close the related Issue when this PR will be merged. I think that you can just replace `mentioned in #44` by `closes #44` and that should do it.

Yeah, I usually use the "resolve" keyword. Don't know why I forgot it this time.

**Comment by didriklundberg** [comment]
> Let's wait for the CI to accept and then "rebase and merge" it in.

Hmm.. While Poly/ML 5.8 succeeds in compiling, 5.7 times out seemingly randomly when compiling `bir_exp_tautologiesScript.sml` to theory. However, I managed to compile everything on my own computer using 5.7.

What do you say, @andreaslindner? If this instability of 5.7 is consistent I don't really see a reason to continue using it.

**Comment by andreaslindner** [comment]
This is surely only a timeout like we discussed in slack. You can either just "rebase and merge" or restart the failing job and wait for it to succeed and then click the merge button. Do as you like, both is fine with me.

But no, the instability is not consistent. Sometimes it is poly 5.7.1 and sometimes it is 5.8. I think since I added 5.8 it was even hanging more than 5.7.1 - my guess is that this is just coincidence though, and that the problem is the same in both of them. But we can drop 5.7.1 I think. The only disadvantage I can see is that the default seems to still be 5.7.1 even in the latest commit of HOL (while we "only" use the latest release version): https://github.com/HOL-Theorem-Prover/HOL/blob/master/developers/install-poly.sh. But this shouldn't matter so much. What do you think?

**Comment by didriklundberg** [comment]
> This is surely only a timeout like we discussed in slack.

Yes, that seems to be the case.

> But no, the instability is not consistent. Sometimes it is poly 5.7.1 and sometimes it is 5.8. I think since I added 5.8 it was even hanging more than 5.7.1 - my guess is that this is just coincidence though, and that the problem is the same in both of them. But we can drop 5.7.1 I think. The only disadvantage I can see is that the default seems to still be 5.7.1 even in the latest commit of HOL (while we "only" use the latest release version): https://github.com/HOL-Theorem-Prover/HOL/blob/master/developers/install-poly.sh. But this shouldn't matter so much. What do you think?

HOL has probably stayed at 5.7.1 just because this is the latest package for Ubuntu. I don't think upgrading is a problem as long as we make sure everything runs fine, but on the other side, if the timeouts are indeed evenly distributed across 5.7.1 and 5.8 I see no reason to upgrade at this time.

**Pull request merged**
